### ISSUE TITLE
Numpy not loading on Binder

### ISSUE THREAD

**Issue by JPBergsma** [Materials-Consortia/optimade-tutorial-exercises#6]
It seems that Binder no longer loads numpy for exercise7-oqmd-optimade-tutorial.ipynb
I'll try to figure out why this happens this weekend.
In the meantime people should use Colab or run the Jupyter notebook locally.

**Comment by tachyontraveler** [comment]
Binder requires that any extra python libraries to installed need to be in a requirements.txt file, as I have included in the original tutorial repo: https://github.com/tachyontraveler/oqmd-optimade-tutorial

**Comment by JPBergsma** [comment]
I had put the requirements.txt file at the same nesting level as the jupyter notebook file. 
Now that I placed it at the top most level it does seem to work.
Although it is still strange that in the past it did work without the requirements file.

**Comment by ml-evs** [comment]
Looks like Binder updated this week (now uses JupyterLab interface by default), so maybe something else has changed under the hood that broke this.
